In [37]:
import graphlab as gl
import pandas as pd!

ImportError: No module named numpy

In [38]:
! conda install -c anaconda numpy

Collecting package metadata: - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done
Solving environment: - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | done

## Package Plan ##

  environment location: /Users/shri/anaconda3/envs/gl-env

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.10.4               |           py27_0         3.0 MB  anaconda
    openssl-1.0.2g             |                0         3.0 MB  anaconda
    ------------------------------------------------------------
                                           Total:         6.0 MB

The following packages will be SUPERSEDED by a higher-priority channel:

  numpy                                           pkgs/free --> anaconda
  openssl                                         pkgs/free --> anaconda


Proceed ([y]/n)? ^C
CondaSystemExit:
Operation aborted.  Exiting.

In [32]:
! pip install --upgrade pandas

Collecting pandas
  Downloading https://files.pythonhosted.org/packages/52/ff/912fe03a623a70bcf297d466013a0b4f4c68c3b60f86bf226682d061fc09/pandas-0.24.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.7MB)
    100% |################################| 16.7MB 32kB/s
Collecting pytz>=2011k (from pandas)
  Downloading https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl (510kB)
    100% |################################| 512kB 480kB/s
Collecting python-dateutil>=2.5.0 (from pandas)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |################################| 235kB 540kB/s
Collecting numpy>=1.12.0 (from pandas)
  Downloading https://files.pythonhosted.org/packages/8f/0b/1a2c21bb69138337dc079841aa4a45e5b2fc7a4260c0907f5254fb08f02e/numpy-1.16.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |################################| 13.9MB 40kB/s
Requirement already up-to-date: six>=1.5 in /Users/shri/anaconda3/envs/gl-env/lib/python2.7/site-packages (from python-dateutil>=2.5.0->pandas)
Installing collected packages: pytz, python-dateutil, numpy, pandas
  Found existing installation: pytz 2016.2
    DEPRECATION: Uninstalling a distutils installed project (pytz) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pytz-2016.2:
      Successfully uninstalled pytz-2016.2
  Found existing installation: python-dateutil 2.7.5
    Uninstalling python-dateutil-2.7.5:
      Successfully uninstalled python-dateutil-2.7.5
  Found existing installation: numpy 1.10.4
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.10.4:
      Successfully uninstalled numpy-1.10.4
  Found existing installation: pandas 0.18.0
    Uninstalling pandas-0.18.0:
      Successfully uninstalled pandas-0.18.0
Successfully installed numpy-1.16.4 pandas-0.24.2 python-dateutil-2.8.0 pytz-2019.1
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [4]:
loans=gl.SFrame('data_set/lending-club-data.gl/')
loans.head(5)

Columns:
	id	int
	member_id	int
	loan_amnt	int
	funded_amnt	int
	funded_amnt_inv	int
	term	str
	int_rate	float
	installment	float
	grade	str
	sub_grade	str
	emp_title	str
	emp_length	str
	home_ownership	str
	annual_inc	int
	is_inc_v	str
	issue_d	str
	loan_status	str
	pymnt_plan	str
	url	str
	desc	str
	purpose	str
	title	str
	zip_code	str
	addr_state	str
	dti	float
	delinq_2yrs	int
	earliest_cr_line	str
	inq_last_6mths	int
	mths_since_last_delinq	int
	mths_since_last_record	int
	open_acc	int
	pub_rec	int
	revol_bal	int
	revol_util	float
	total_acc	int
	initial_list_status	str
	out_prncp	float
	out_prncp_inv	float
	total_pymnt	float
	total_pymnt_inv	float
	total_rec_prncp	float
	total_rec_int	float
	total_rec_late_fee	float
	recoveries	float
	collection_recovery_fee	float
	last_pymnt_d	str
	last_pymnt_amnt	float
	next_pymnt_d	str
	last_credit_pull_d	str
	collections_12_mths_ex_med	int
	mths_since_last_major_derog	str
	policy_code	int
	not_compliant	int
	status	str
	inactive_loans	int
	bad_loans	int
	emp_length_num	int
	grade_num	int
	sub_grade_num	float
	delinq_2yrs_zero	int
	pub_rec_zero	int
	collections_12_mths_zero	int
	short_emp	int
	payment_inc_ratio	float
	final_d	str
	last_delinq_none	int
	last_record_none	int
	last_major_derog_none	int

Rows: 5

Data:
+---------+-----------+-----------+-------------+-----------------+------------+
|    id   | member_id | loan_amnt | funded_amnt | funded_amnt_inv |    term    |
+---------+-----------+-----------+-------------+-----------------+------------+
| 1077501 |  1296599  |    5000   |     5000    |       4975      |  36 months |
| 1077430 |  1314167  |    2500   |     2500    |       2500      |  60 months |
| 1077175 |  1313524  |    2400   |     2400    |       2400      |  36 months |
| 1076863 |  1277178  |   10000   |    10000    |      10000      |  36 months |
| 1075269 |  1311441  |    5000   |     5000    |       5000      |  36 months |
+---------+-----------+-----------+-------------+-----------------+------------+
+----------+-------------+-------+-----------+----------------------+------------+
| int_rate | installment | grade | sub_grade |      emp_title       | emp_length |
+----------+-------------+-------+-----------+----------------------+------------+
|  10.65   |    162.87   |   B   |     B2    |                      | 10+ years  |
|  15.27   |    59.83    |   C   |     C4    |        Ryder         |  < 1 year  |
|  15.96   |    84.33    |   C   |     C5    |                      | 10+ years  |
|  13.49   |    339.31   |   C   |     C1    | AIR RESOURCES BOARD  | 10+ years  |
|   7.9    |    156.46   |   A   |     A4    | Veolia Transportaton |  3 years   |
+----------+-------------+-------+-----------+----------------------+------------+
+----------------+------------+-----------------+-----------------+-------------+
| home_ownership | annual_inc |     is_inc_v    |     issue_d     | loan_status |
+----------------+------------+-----------------+-----------------+-------------+
|      RENT      |   24000    |     Verified    | 20111201T000000 |  Fully Paid |
|      RENT      |   30000    | Source Verified | 20111201T000000 | Charged Off |
|      RENT      |   12252    |   Not Verified  | 20111201T000000 |  Fully Paid |
|      RENT      |   49200    | Source Verified | 20111201T000000 |  Fully Paid |
|      RENT      |   36000    | Source Verified | 20111201T000000 |  Fully Paid |
+----------------+------------+-----------------+-----------------+-------------+
+------------+-------------------------------+-------------------------------+-----+
| pymnt_plan |              url              |              desc             | ... |
+------------+-------------------------------+-------------------------------+-----+
|     n      | https://www.lendingclub.co... |   Borrower added on 12/22/... | ... |
|     n      | https://www.lendingclub.co... |   Borrower added on 12/22/... | ... |
|     n      | https://www.lendingclub.co... |                               | ... |
|     n      | https://www.lendingclub.co... |   Borrower added on 12/21/... | ... |
|     n      | https://www.lendingclub.co... |                               | ... |
+------------+-------------------------------+-------------------------------+-----+
[5 rows x 68 columns]

In [9]:
# Reassigning the labels for Safe and Risky loans
loans['safe_loans']=loans['bad_loans'].apply(lambda x:+1 if x==0 else -1)
loans=loans.remove_column('bad_loans')

In [10]:
# Considering only 4 features
features = ['grade',              # grade of the loan
            'term',               # the term of the loan
            'home_ownership',     # home_ownership status: own, mortgage or rent
            'emp_length',         # number of years of employment
           ]
target = 'safe_loans'

In [14]:
# Extracting the data with required features
loans=loans[features+[target]]
loans.dtype

<bound method SFrame.dtype of Columns:
	grade	str
	term	str
	home_ownership	str
	emp_length	str
	safe_loans	int

Rows: 122607

Data:
+-------+------------+----------------+------------+------------+
| grade |    term    | home_ownership | emp_length | safe_loans |
+-------+------------+----------------+------------+------------+
|   B   |  36 months |      RENT      | 10+ years  |     1      |
|   C   |  60 months |      RENT      |  < 1 year  |     -1     |
|   C   |  36 months |      RENT      | 10+ years  |     1      |
|   C   |  36 months |      RENT      | 10+ years  |     1      |
|   A   |  36 months |      RENT      |  3 years   |     1      |
|   E   |  36 months |      RENT      |  9 years   |     1      |
|   F   |  60 months |      OWN       |  4 years   |     -1     |
|   B   |  60 months |      RENT      |  < 1 year  |     -1     |
|   C   |  60 months |      OWN       |  5 years   |     1      |
|   B   |  36 months |      OWN       | 10+ years  |     1      |
+-------+------------+----------------+------------+------------+
[122607 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.>

## Subsample dataset to make sure classes are balanced

In [15]:
safe_loans_raw=loans[loans[target]==1]
risky_loans_raw=loans[loans[target]==-1]

# Since there are less risky loans than safe loans, find the ratio of the sizes
#and use that percentage to undersample the safe loans.
percentage=len(risky_loans_raw)/float(len(safe_loans_raw))
safe_loans = safe_loans_raw.sample(percentage,seed=1)
risky_loans=risky_loans_raw
loans_data=risky_loans.append(safe_loans)

## Transforming Categorical data in binary features

In [20]:
loans_data.column_names

<bound method SFrame.column_names of Columns:
	grade	str
	term	str
	home_ownership	str
	emp_length	str
	safe_loans	int

Rows: 46508

Data:
+-------+------------+----------------+------------+------------+
| grade |    term    | home_ownership | emp_length | safe_loans |
+-------+------------+----------------+------------+------------+
|   C   |  60 months |      RENT      |  < 1 year  |     -1     |
|   F   |  60 months |      OWN       |  4 years   |     -1     |
|   B   |  60 months |      RENT      |  < 1 year  |     -1     |
|   C   |  36 months |      RENT      |  < 1 year  |     -1     |
|   B   |  36 months |      RENT      |  3 years   |     -1     |
|   B   |  36 months |      RENT      | 10+ years  |     -1     |
|   B   |  36 months |      RENT      |   1 year   |     -1     |
|   C   |  36 months |      RENT      |  9 years   |     -1     |
|   D   |  60 months |      RENT      |  2 years   |     -1     |
|   A   |  36 months |    MORTGAGE    | 10+ years  |     -1     |
+-------+------------+----------------+------------+------------+
[46508 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.>